Repository AY2223S2-CS2113-W12-1/tp, pull requests merged in 2023-03, with the labels that each got.

#20 Renaming Sniff Classes and Variables
  build.gradle
  src/main/java/functionalities/Command.java
  src/main/java/functionalities/Parser.java
  src/main/java/functionalities/SniffTasks.java
  src/main/java/functionalities/Ui.java
  src/main/java/seedu/sniff/Sniff.java
  src/test/java/seedu/sniff/SniffTest.java
Labels: type.Task, priority.Medium

#23 Edit user interface message for listing appointment
  src/main/java/functionalities/SniffTasks.java
  src/main/java/functionalities/Ui.java
Labels: type.Story, priority.High

#37 Updated appointments
  src/main/java/functionalities/Animal.java
  src/main/java/functionalities/Consultation.java
  src/main/java/functionalities/Owner.java
  src/main/java/functionalities/Surgery.java
  src/main/java/functionalities/Vaccination.java
  src/main/java/functionalities/newAppointment.java
Labels: type.Enhancement, priority.High

#38 Update appointments
  src/main/java/functionalities/Consultation.java
  src/main/java/functionalities/Surgery.java
  src/main/java/functionalities/Vaccination.java
  src/main/java/functionalities/newAppointment.java
Labels: type.Enhancement, priority.Medium

#42 UID generator
  build.gradle
  src/main/java/functionalities/Appointment.java
  src/main/java/functionalities/SniffTasks.java
  src/main/java/functionalities/Ui.java
  src/main/java/functionalities/Uid.java
  src/main/java/functionalities/commands/ConsulationCommand.java
  src/main/java/functionalities/commands/RemoveCommand.java
  src/main/java/functionalities/commands/SurgeryCommand.java
  src/main/java/functionalities/commands/VaccinationCommand.java
  src/test/java/seedu/sniff/UidGeneratorTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.High

#48 Change HashMap implementation of storing the UIDs to HashSet
  src/main/java/functionalities/SniffTasks.java
Labels: type.Bug, priority.High, severity.High

#52 Add guard clauses for UID generator
  src/main/java/exception/SniffException.java
  src/main/java/functionalities/Uid.java
  src/test/java/seedu/sniff/UidGeneratorTest.java
Labels: priority.Medium

#58 Update the Developer Guide to document the appropriate sections
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#62 Implemented storage functionality
  src/main/java/functionalities/Animal.java
  src/main/java/functionalities/Owner.java
  src/main/java/functionalities/SniffTasks.java
  src/main/java/functionalities/appointments/Appointment.java
  src/main/java/functionalities/appointments/Consultation.java
  src/main/java/functionalities/appointments/Surgery.java
  src/main/java/functionalities/appointments/Vaccination.java
  src/main/java/functionalities/parser/FileParser.java
  src/main/java/functionalities/storage/Storage.java
  src/main/java/functionalities/ui/Ui.java
  src/main/java/seedu/sniff/Sniff.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#63 Implementing parser for mark and unmark command
  src/main/java/functionalities/parser/Parser.java
  src/main/java/functionalities/storage/Storage.java
  src/main/java/seedu/sniff/Sniff.java
Labels: priority.High
